---
title: "ML Homework 2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown



```{r cars}
training.data.raw <- read.csv('documents/train_titanic.csv',header=T,na.strings=c(""))
head(training.data.raw)
sapply(training.data.raw, function(x) length(unique(x)))

library(Amelia)
missmap(training.data.raw, main = "Missing values vs observed")

datasub <- subset(training.data.raw,select=c(2,3,5,6,7,8,10,12))
```

```{r cars}
#relace null with average
#read.csv and read.table will encode the categorical variables as factors.
data$Age[is.na(data$Age)] <- mean(data$Age,na.rm=T)

is.factor(data$Sex)
is.factor(data$Embarked)
contrasts(data$Sex)
contrasts(data$Embarked)

#replacing blank values
data <- data[!is.na(data$Embarked),]
rownames(data) <- NULL


trainxx <- data[1:800,]
testxx <- data[801:889,]

model_titanic <- glm(Survived ~.,family=binomial(link='logit'),data=train)
summary(model_titanic)
```

```{r cars}
#logistic regression in R
rawtrainx <- read.csv('documents/onion_vs_economist_2/Xtrain.csv',header=T,na.strings=c(""))
rawtrainy <- read.csv('documents/onion_vs_economist_2/Ytrain.csv',header=T,na.strings=c(""))

rawvocab <-read.csv('documents/onion_vs_economist_2/vocabulary.csv',header=T,na.strings=c(""))
rawtrainx<-data.frame(rawtrainx)
head(rawtrainx)
sapply(rawtrainx, function(x) length(unique(x)))

library(Amelia)
missmap(rawtrainx, main = "Missing values vs observed")

library(plyr)

count(rawtrainx, vars = NULL, wt_var = NULL)
head(rawtrainx)
summary(rawtrainx)

sapply(rawtrainx,function(x) sum(is.na(x)))


head(rawtrainy)
rawtrainy<-data.frame(rawtrainy)
colnames(rawtrainy) <- "classpredict"

masterset<-cbind(rawtrainx, rawtrainy)
head(masterset)
#masterset.mat<- data.matrix(masterset)
temp = read.csv('documents/onion_vs_economist_2/Xtrain.csv', sep=",", row.names=NULL)
xtrainmat <- as.matrix(temp) 
temp2 = read.csv('documents/onion_vs_economist_2/Ytrain.csv', sep=",", row.names=NULL)
ytrainmat <- as.matrix(temp2) 
totalmat<-cbind2(xtrainmat, ytrainmat)
model.log1 <- glm(classpredict ~.,family=binomial(link='logit'),data=totalmat)
```
